version: '3.8'
services:
  server:
    container_name: vitality_server
    image: alexeipc/vitality_server
    build: ./server
    ports:
    - published: 5000
      target: 5000
    environment:
      DATABASE_URI: ${DATABASE_URI}
    deploy:
      replicas: 2
  msdays_api:
    container_name: msdays_api
    image: alexeipc/msdays_api
    build: ./msdays
  msindoor_api:
    container_name: msindoor_api
    image: alexeipc/msindoor_api
    build: ./msindoor
  msimprovement_api:
    container_name: msimprovement_api
    image: alexeipc/msimprovement_api
    build: ./msimprovement
  