all:
  children:
    managers:
      hosts:
        swarm-manager:
    workers:
      hosts:
        swarm-worker:
        swarm-worker2:
    nginx:
      hosts:
        nginx: 

  vars:
    ansible_python_interpreter: "/usr/bin/python3"