- hosts: all
  become: true
  vars:
    ansible_host_key_checking: false
  roles:
  - including_vars
  - install-docker

- hosts: managers
  become: true
  roles:
  - swarm-manager

- hosts: workers
  become: true
  roles:
  - swarm-worker

- hosts: nginx
  become: true
  roles:
  - nginx