pipeline {
    agent any
    environment {
        DATABASE_URI = credentials("DATABASE_URI")
        SECRET_KEY = credentials("SECRET_KEY")
        DOCKER_LOGIN = credentials("DOCKER_LOGIN")
    }
    stages {
        stage('Test') {
            steps {
                sh 'bash jenkins/test.sh'
            }
        }
        stage('Build Docker') {
            steps {
                sh 'bash jenkins/dockerbuild.sh'
            }
        }
        stage('Push') {
            steps {
               sh 'docker push alexeipc/projectvitality:latest'
            }
        }    
    }
    post {
        always {
            junit '**/*.xml'
            cobertura coberturaReportFile: 'coverage.xml', failNoReports: false
        }
    }
}