pipeline {
    agent any
    environment {
        DATABASE_URI = credentials("DATABASE_URI")
        SECRET_KEY = credentials("SECRET_KEY")
        DOCKER_LOGIN = credentials("DOCKER_LOGIN")
    }
    stages {
        stage('Tests') {
            steps {
                sh 'bash jenkins/test.sh'
            }
        }
        stage('Build Docker') {
            steps {
                sh 'bash jenkins/dockerbuild.sh'
            }
        }
        stage('Push Docker') {
            steps {
                sh 'docker push alexeipc/vitality_server:latest'
                sh 'docker push alexeipc/msdays_api:latest'
                sh 'docker push alexeipc/msindoor_api:latest'
            } 
        }
        stage('Deployment - Ansible') {
            steps {
                sh 'ansible-playbook -i ansible/roles/inventory.yaml playbook.yaml'
            }
        }
    }
    post {
        always {
            junit '**/*.xml'
            cobertura coberturaReportFile: 'coverage.xml', failNoReports: false
        }
    }
}