---
- name: "Install nginx"
  apt:
    pkg:
    - nginx
    state: latest
    update_cache: true

- name: "Start nginx service"
  service:
    name: nginx
    state: started

- name: "install ngnix.conf"
  template:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
  notify: 'reload nginx'