---
- name: "Install dependencies"
  apt:
    pkg:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg
    - lsb-release
    - python3
    - python3-pip
    state: latest
    update_cache: true
      
- name: "Get Docker APT key"
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: "Add Docker APT Repository"
  ansible.builtin.apt_repository:
    repo: "deb https://download.docker.com/linux/ubuntu bionic stable"
    state: present

- name: "Install Docker on Python"
  pip:
    name: docker

- name: "Install Docker"
  apt:
    pkg:
    - docker-ce
    - docker-ce-cli
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg
    - lsb-release

- name: "Add User to Docker Group"
  ansible.builtin.user:
    name: jenkins
    groups: docker
    append: yes
