---
- name: "Add worker to Swarm"
  docker_swarm:
    state: join
    advertise_addr: swarm-worker swarm-worker2
    join_token: "{{ hostvars[groups['managers'][0]['swarm_info']['swarm_facts']['JoinTokens']['Worker']] }}"
    remote_addrs: "{{ groups['managers'][0] }}"